import { useEffect } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { invokeEdgeFunction } from "@/lib/edge-invoke";

/**
 * Decides whether a wine's image_url is a "real" label image (uploaded by the
 * user or generated by our AI and stored in our bucket) vs a placeholder/empty
 * value that should be resolved.
 */
function hasRealImage(url: string | null | undefined): boolean {
  if (!url) return false;
  const lower = url.toLowerCase();
  if (lower.startsWith("data:image/svg+xml")) return false; // illustrative svg
  if (/alert\.jpg|placeholder|notfound|not[-_]?found|404\.|missing/i.test(url)) return false;
  return true;
}

// In-memory dedupe across renders + simple sessionStorage persistence so we
// don't re-trigger generation for the same wine over and over while browsing.
const inflight = new Set<string>();
const FAILED_KEY = "sommelyx_image_resolve_failed_v1";
function getFailed(): Set<string> {
  try {
    const raw = sessionStorage.getItem(FAILED_KEY);
    if (!raw) return new Set();
    const arr = JSON.parse(raw) as string[];
    return new Set(arr);
  } catch {
    return new Set();
  }
}
function markFailed(wineId: string) {
  try {
    const set = getFailed();
    set.add(wineId);
    sessionStorage.setItem(FAILED_KEY, JSON.stringify([...set]));
  } catch {
    /* ignore */
  }
}

// Concurrency limiter: only N image resolutions in flight at once.
const MAX_PARALLEL = 2;
let active = 0;
const queue: Array<() => void> = [];

function schedule(task: () => Promise<void>) {
  const run = async () => {
    active++;
    try {
      await task();
    } finally {
      active--;
      const next = queue.shift();
      if (next) next();
    }
  };
  if (active < MAX_PARALLEL) {
    void run();
  } else {
    queue.push(() => void run());
  }
}

interface MinimalWine {
  id: string;
  image_url: string | null;
}

/**
 * Lazily asks the wine-image-resolver edge function to generate / fetch a
 * label image for any wine in the list that doesn't have a real image yet.
 *
 * - Skips wines that already have a real image (uploaded or AI-generated).
 * - Dedupes per session so we never spam the function.
 * - Limits concurrency to keep the AI gateway happy.
 * - Invalidates the wines query on success so the new image shows up.
 */
export function useAutoResolveWineImages(wines: MinimalWine[] | undefined) {
  const queryClient = useQueryClient();

  useEffect(() => {
    if (!wines || wines.length === 0) return;

    const failed = getFailed();
    const targets = wines.filter(
      (w) => !hasRealImage(w.image_url) && !inflight.has(w.id) && !failed.has(w.id),
    );
    if (targets.length === 0) return;

    targets.forEach((wine) => {
      inflight.add(wine.id);
      schedule(async () => {
        try {
          await invokeEdgeFunction(
            "wine-image-resolver",
            { wineId: wine.id },
            { timeoutMs: 60_000, retries: 0 },
          );
          // Refresh wines so the newly stored image_url is picked up.
          queryClient.invalidateQueries({ queryKey: ["wines"] });
        } catch (err) {
          console.warn("auto wine-image-resolver failed:", wine.id, err);
          markFailed(wine.id);
        } finally {
          inflight.delete(wine.id);
        }
      });
    });
    // We intentionally depend on a stable string of ids so we re-evaluate when
    // the list itself changes, not on every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [wines?.map((w) => `${w.id}:${w.image_url ? 1 : 0}`).join("|")]);
}
