// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupportedStorage, StorageKey } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getRequiredClientEnv } from "@/lib/env";

const SUPABASE_URL =
  getRequiredClientEnv("VITE_SUPABASE_URL") ||
  "https://xhjcwxspndvcsgdlmaqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  getRequiredClientEnv("VITE_SUPABASE_PUBLISHABLE_KEY") ||
  getRequiredClientEnv("VITE_SUPABASE_ANON_KEY") ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoamN3eHNwbmR2Y3NnZGxtYXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMzQxNjEsImV4cCI6MjA4NzYxMDE2MX0.FDcg9CBpj40OlK69Y-jhu7IOsg4P4J5W27VoT3HZqYM";

const memoryStorage = new Map<string, string>();

const safeStorage: SupportedStorage = {
  getItem(key: StorageKey) {
    try {
      return window.localStorage.getItem(key) ?? memoryStorage.get(key) ?? null;
    } catch {
      return memoryStorage.get(key) ?? null;
    }
  },
  setItem(key: StorageKey, value: string) {
    memoryStorage.set(key, value);
    try {
      window.localStorage.setItem(key, value);
    } catch {
      // Ignore storage write failures and keep the in-memory session as fallback.
    }
  },
  removeItem(key: StorageKey) {
    memoryStorage.delete(key);
    try {
      window.localStorage.removeItem(key);
    } catch {
      // Ignore storage cleanup failures.
    }
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
    storageKey: "sommelyx.auth.token",
  },
});
